name: cifar100
input_size: 224  # Resize to match pretrained model input size
mean: [0.5071, 0.4867, 0.4408]
std: [0.2675, 0.2565, 0.2761]
num_classes: 100
augmentation:
  random_resized_crop: false
  random_resized_crop_scale: [0.08, 1.0]
  random_resized_crop_ratio: [0.75, 1.3333333333333333]
  random_crop: true
  random_horizontal_flip: true
  color_jitter: false
  auto_augment: false
  auto_augment_policy: "cifar10"
  test_center_crop: false
  normalize: true
