name: cub200
input_size: 224  # Resize to match pretrained model input size
mean: [0.485, 0.456, 0.406]  # ImageNet mean
std: [0.229, 0.224, 0.225]   # ImageNet std
num_classes: 200
augmentation:
  random_crop: true
  random_horizontal_flip: true
  color_jitter: true
  auto_augment: false
