name: imagenet-r
input_size: 224  # Resize to match pretrained model input size
mean: [0.485, 0.456, 0.406]  # ImageNet mean
std: [0.229, 0.224, 0.225]   # ImageNet std
num_classes: 200
train_ratio: 0.8  # Ratio of data to use for training (since ImageNet-R doesn't have a train/test split)
augmentation:
  random_resized_crop: true
  random_crop: false
  random_horizontal_flip: true
  color_jitter: true
  auto_augment: false
  auto_augment_policy: "imagenet"
