name: objectnet200
input_size: 224  # Resize to match pretrained model input size
use_pretrained_norm: true
mean: [0.485, 0.456, 0.406]  # ImageNet mean
std: [0.229, 0.224, 0.225]   # ImageNet std
num_classes: 200  # ObjectNet-200 subset with 200 classes
augmentation:
  random_resized_crop: true
  random_resized_crop_scale: [0.08, 1.0]
  random_resized_crop_ratio: [0.75, 1.3333333333333333]
  random_crop: false
  random_horizontal_flip: true
  color_jitter: true
  auto_augment: false
  auto_augment_policy: "imagenet"
  test_center_crop: true
  normalize: true
