name: vtab
input_size: 224  # Resize to match pretrained model input size
use_pretrained_norm: true
apply_moment_matching: false
mean: [0.485, 0.456, 0.406]  # ImageNet mean
std: [0.229, 0.224, 0.225]   # ImageNet std
num_classes: 100  # Number of classes (single task option)
task: cifar100  # VTAB task (single task option)
# Available tasks:
# - cifar100 (100 classes)
# - caltech101 (102 classes)
# - dtd (47 classes)
# - oxford_flowers102 (102 classes)
# - oxford_iiit_pet (37 classes)
# - sun397 (397 classes)
# - svhn (10 classes)
# - patch_camelyon (2 classes)
# - eurosat (10 classes)
# - resisc45 (45 classes)
# - diabetic_retinopathy (5 classes)
# - clevr_count (8 classes)
# - clevr_distance (6 classes)
# - dmlab (6 classes)
# - kitti (4 classes)
# - smallnorb_azimuth (18 classes)
# - smallnorb_elevation (9 classes)
# - dsprites_orientation (16 classes)
# - dsprites_location (16 classes)
# - merged (for merging multiple task datasets)

# For merged dataset option, specify task subsets and number of classes to use from each
# Example:
# merged_task_subsets:
#   resisc45: 10
#   dtd: 10
#   oxford_iiit_pet: 10
#   eurosat: 10
#   oxford_flowers102: 10
# Leave empty to use the single task specified above
merged_task_subsets:
  resisc45: 10
  dtd: 10
  oxford_iiit_pet: 10
  eurosat: 10
  oxford_flowers102: 10
augmentation:
  random_resized_crop: true
  random_resized_crop_scale: [0.08, 1.0]
  random_resized_crop_ratio: [0.75, 1.3333333333333333]
  random_crop: false
  random_horizontal_flip: true
  color_jitter: false
  auto_augment: false
  auto_augment_policy: "imagenet"
  test_center_crop: true
  normalize: true
  moment_matching:
    pretraining_data_mean: [0.4845, 0.4541, 0.4025]
    pretraining_data_std: [0.2724, 0.2637, 0.2761]

